/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Controlador.Controlador;
import ModeloDeDados.Constantes;
import ModeloDeDados.Departamento;
import ModeloDeDados.Efetivo;
import ModeloDeDados.Funcionário;
import ModeloDeDados.Substituto;
import ModeloDeDados.Tecnico;
import javax.swing.JOptionPane;

/**
 *
 * @author Cauan
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        funNome = new javax.swing.JTextField();
        funTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        funDepartamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        depNome = new javax.swing.JTextField();
        cadastrarDep = new javax.swing.JButton();
        cadastrarFun = new javax.swing.JButton();
        funFuncao = new javax.swing.JComboBox<>();
        funTitulacao = new javax.swing.JComboBox<>();
        funArea = new javax.swing.JComboBox<>();
        funCargaH = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        funNivel = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        relatorioGeral = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        relatorioDeps = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        escolhaDep = new javax.swing.JComboBox<>();
        faixaFim = new javax.swing.JTextField();
        faixaIni = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        relatorioFun = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaTexto4 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        escolhaFun = new javax.swing.JComboBox<>();
        faixaFimFun = new javax.swing.JTextField();
        faixaIniFun = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        buscarDep = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaTexto5 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        buscarDepartamento = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        buscarFunCodNome = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        areaTexto6 = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        buscarCod = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        buscarNome = new javax.swing.JTextField();
        buscarFun = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidade");
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("UNIVERSIDADE");

        jTabbedPane3.setBackground(new java.awt.Color(255, 204, 51));
        jTabbedPane3.setName("Cadastrar Funcionário"); // NOI18N

        jPanel2.setName(""); // NOI18N

        jLabel3.setText("Nome");

        jLabel5.setText("Nível");

        funNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funNomeActionPerformed(evt);
            }
        });

        funTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Técnico", "Efetivo", "Substituto" }));
        funTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funTipoActionPerformed(evt);
            }
        });

        jLabel4.setText("Função");

        jLabel6.setText("Titulação");

        funDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funDepartamentoActionPerformed(evt);
            }
        });

        jLabel7.setText("Área");

        jLabel8.setText("Carga Horária");

        jLabel9.setText("ID do departamento");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Departamento:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Funcionário:");

        jLabel12.setText("Nome");

        depNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depNomeActionPerformed(evt);
            }
        });

        cadastrarDep.setBackground(new java.awt.Color(255, 204, 51));
        cadastrarDep.setText("Cadastrar Departamento");
        cadastrarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarDepActionPerformed(evt);
            }
        });

        cadastrarFun.setBackground(new java.awt.Color(255, 204, 51));
        cadastrarFun.setText("Cadastrar Funcionário");
        cadastrarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFunActionPerformed(evt);
            }
        });

        funFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Assessor", "Laboratório", "Secretário" }));

        funTitulacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Graduação", "Mestrado", "Doutorado", "Livre-Docente", "Titular" }));
        funTitulacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funTitulacaoActionPerformed(evt);
            }
        });

        funArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Biológicas", "Exatas", "Humanas", "Saúde" }));
        funArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funAreaActionPerformed(evt);
            }
        });

        funCargaH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "12", "24" }));
        funCargaH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funCargaHActionPerformed(evt);
            }
        });

        jLabel13.setText("Tipo de funcionário");

        funNivel.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(depNome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134)
                                .addComponent(cadastrarDep)))
                        .addContainerGap(453, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funNome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(14, 14, 14)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(funTitulacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(funFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(funDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(funCargaH, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(funArea, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(249, 249, 249))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(cadastrarFun)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarDep))
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(funFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(funNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(funTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(funTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(funCargaH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(funDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(funNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(cadastrarFun)
                .addGap(62, 62, 62))
        );

        jTabbedPane3.addTab("Cadastrar Funcionário ou Departamento", jPanel2);

        areaTexto.setBackground(new java.awt.Color(255, 255, 204));
        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        relatorioGeral.setBackground(new java.awt.Color(255, 204, 51));
        relatorioGeral.setText("Relatório Geral");
        relatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioGeralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relatorioGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(relatorioGeral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Relatório Geral", jPanel4);

        relatorioDeps.setBackground(new java.awt.Color(255, 204, 51));
        relatorioDeps.setText("Resumo dos departamentos");
        relatorioDeps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioDepsActionPerformed(evt);
            }
        });

        areaTexto2.setBackground(new java.awt.Color(255, 255, 204));
        areaTexto2.setColumns(20);
        areaTexto2.setRows(5);
        jScrollPane2.setViewportView(areaTexto2);

        jLabel14.setText("Faixa inicial");

        jLabel15.setText("Faixa final");

        escolhaDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Faixa específica" }));
        escolhaDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolhaDepActionPerformed(evt);
            }
        });

        faixaFim.setEnabled(false);

        faixaIni.setEnabled(false);
        faixaIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faixaIniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faixaIni, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(faixaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(relatorioDeps, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(escolhaDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relatorioDeps)
                    .addComponent(escolhaDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(faixaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(faixaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Resumo dos departamentos", jPanel5);

        relatorioFun.setBackground(new java.awt.Color(255, 204, 51));
        relatorioFun.setText("Resumo dos funcionários");
        relatorioFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioFunActionPerformed(evt);
            }
        });

        areaTexto4.setBackground(new java.awt.Color(255, 255, 204));
        areaTexto4.setColumns(20);
        areaTexto4.setRows(5);
        jScrollPane4.setViewportView(areaTexto4);

        jLabel18.setText("Faixa inicial");

        jLabel19.setText("Faixa final");

        escolhaFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Faixa específica", "Técnicos", "Docentes", "Docentes efetivos", "Docentes substitutos" }));
        escolhaFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolhaFunActionPerformed(evt);
            }
        });

        faixaFimFun.setEnabled(false);

        faixaIniFun.setEnabled(false);
        faixaIniFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faixaIniFunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(faixaIniFun, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(faixaFimFun, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(143, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(relatorioFun, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(escolhaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(relatorioFun)
                    .addComponent(escolhaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(faixaFimFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faixaIniFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Resumo dos funcionários", jPanel6);

        buscarDep.setBackground(new java.awt.Color(255, 204, 51));
        buscarDep.setText("Resumo dos departamento informado pelo código");
        buscarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDepActionPerformed(evt);
            }
        });

        areaTexto5.setBackground(new java.awt.Color(255, 255, 204));
        areaTexto5.setColumns(20);
        areaTexto5.setRows(5);
        jScrollPane5.setViewportView(areaTexto5);

        jLabel20.setText("Código");

        buscarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buscarDep, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(buscarDep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(buscarDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Buscar departamento", jPanel7);

        buscarFunCodNome.setBackground(new java.awt.Color(255, 204, 51));
        buscarFunCodNome.setText("Resumo do funcionário");
        buscarFunCodNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFunCodNomeActionPerformed(evt);
            }
        });

        areaTexto6.setBackground(new java.awt.Color(255, 255, 204));
        areaTexto6.setColumns(20);
        areaTexto6.setRows(5);
        jScrollPane6.setViewportView(areaTexto6);

        jLabel21.setText("Código");

        buscarCod.setEnabled(false);
        buscarCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCodActionPerformed(evt);
            }
        });

        jLabel22.setText("Nome");

        buscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNomeActionPerformed(evt);
            }
        });

        buscarFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código" }));
        buscarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarCod, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(143, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(buscarFunCodNome, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarFunCodNome)
                    .addComponent(buscarFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(buscarCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(buscarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Buscar funcionário", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane3)
                .addGap(16, 16, 16))
        );

        jTabbedPane3.getAccessibleContext().setAccessibleName("Cadastrar Funcionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void faixaIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faixaIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faixaIniActionPerformed

    private void escolhaDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolhaDepActionPerformed

        if (escolhaDep.getSelectedItem() == "Todos"){
            faixaIni.setEnabled(false);
            faixaFim.setEnabled(false);
        }

        else {
            faixaIni.setEnabled(true);
            faixaFim.setEnabled(true);
        }

    }//GEN-LAST:event_escolhaDepActionPerformed

    private void relatorioDepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioDepsActionPerformed

        Controlador controlador = new Controlador();

        if (escolhaDep.getSelectedItem() == "Todos"){

            String relatorio = controlador.ResumoDosDepartamentos();

            areaTexto2.setText(relatorio);

        }

        else {

            try {
                double faixaInicial = Double.parseDouble(faixaIni.getText());
                double faixaFinal = Double.parseDouble(faixaFim.getText());

                if (faixaInicial < faixaFinal){
                    String relatorio = controlador.ResumoDosDepartamentosComGastoEmFaixaEspecífica(faixaInicial, faixaFinal);

                    areaTexto2.setText(relatorio);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Faixas informadas incoerentes");
                }
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Informe as faixas");
            }

        }

    }//GEN-LAST:event_relatorioDepsActionPerformed

    private void relatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioGeralActionPerformed

        Controlador controlador = new Controlador();

        String relatorio = controlador.Geral();

        areaTexto.setText(relatorio);
    }//GEN-LAST:event_relatorioGeralActionPerformed

    private void funCargaHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funCargaHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funCargaHActionPerformed

    private void funAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funAreaActionPerformed

    private void funTitulacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funTitulacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funTitulacaoActionPerformed

    private void cadastrarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFunActionPerformed

        Controlador control = new Controlador();

        String dep = funDepartamento.getText();
        int verificar = control.verificarSeExisteDepartamento(dep);
        String nome = funNome.getText();
        
        
        if (verificar == 1 && !"".equals(nome) && funTipo.getSelectedItem() != "Escolha"){

            if (funTipo.getSelectedIndex() != 0 && funNivel.getSelectedItem() != "Escolha"){

                try {

                    if (funTipo.getSelectedIndex() == 1 && funFuncao.getSelectedItem() != "Escolha"){ // Tecnico
                        String nivel = (String) funNivel.getSelectedItem();
                        String funcao = (String) funFuncao.getSelectedItem();

                        Funcionário func = new Tecnico(funcao, nome, nivel);
                        control.AdicionarFuncionario(func, dep);
                        int id = Constantes.ID - 1;
                        JOptionPane.showMessageDialog(null, "Funcionário cadastrado com ID: " + id);

                    }

                    else if (funTipo.getSelectedIndex() == 2 && funTitulacao.getSelectedItem() != "Escolha" && funArea.getSelectedItem() != "Escolha"){ // Efetivo
                        String nivel = (String) funNivel.getSelectedItem();
                        String funcao = (String) funFuncao.getSelectedItem();
                        String titulacao = (String) funTitulacao.getSelectedItem();
                        String area = (String) funArea.getSelectedItem();

                        Funcionário func = new Efetivo(nome, nivel, area, titulacao);
                        control.AdicionarFuncionario(func, dep);
                        int id = Constantes.ID - 1;
                        JOptionPane.showMessageDialog(null, "Funcionário cadastrado com ID: " + id);
                    }

                    else if (funTipo.getSelectedIndex() == 3 && funTitulacao.getSelectedItem() != "Escolha" && funCargaH.getSelectedItem() != "Escolha"){  // Substitutivo
                        String nivel = (String) funNivel.getSelectedItem();
                        String funcao = (String) funFuncao.getSelectedItem();
                        String titulacao = (String) funTitulacao.getSelectedItem();
                        int cargaH = Integer.parseInt((String) funCargaH.getSelectedItem());

                        Funcionário func = new Substituto(cargaH, nome, nivel, titulacao);
                        control.AdicionarFuncionario(func, dep);
                        int id = Constantes.ID - 1;
                        JOptionPane.showMessageDialog(null, "Funcionário cadastrado com ID: " + id);
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Algum campo não foi preenchido corretamente");

                }

            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Há conteúdo não preenchido ou o departamento especificado não foi encontrado");
        }
    }//GEN-LAST:event_cadastrarFunActionPerformed

    private void cadastrarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarDepActionPerformed

        Controlador controle = new Controlador();

        try {

            String nomeDep = depNome.getText();

            if (!"".equals(nomeDep)){
                Departamento dep = new Departamento(nomeDep);
                
                controle.AdicionarDepartamento(dep);
                int id = Constantes.codDEP - 1;
                
                JOptionPane.showMessageDialog(null, "Departamento criado com ID: " + id);
                

            }
            else {
                JOptionPane.showMessageDialog(null, "Informe o nome do departamento");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algum campo não foi preenchido corretamente");
        }
    }//GEN-LAST:event_cadastrarDepActionPerformed

    private void depNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depNomeActionPerformed

    private void funDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funDepartamentoActionPerformed

    private void funTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funTipoActionPerformed

        
        if (funTipo.getSelectedItem() == "Escolha"){
            funNivel.setEnabled(false);
        }
        
        else if (funTipo.getSelectedItem() == "Técnico"){

            funNivel.setEnabled(true);
            funFuncao.setEnabled(true);
            funTitulacao.setEnabled(false);
            funArea.setEnabled(false);
            funCargaH.setEnabled(false);

            funNivel.removeAllItems();
            funNivel.addItem ("T1");
            funNivel.addItem ("T2");

        }

        else if (funTipo.getSelectedItem() == "Efetivo"){

            funNivel.setEnabled(true);
            funFuncao.setEnabled(false);
            funTitulacao.setEnabled(true);
            funArea.setEnabled(true);
            funCargaH.setEnabled(false);

            funNivel.removeAllItems();
            funNivel.addItem ("D1");
            funNivel.addItem ("D2");
            funNivel.addItem ("D3");

        }

        else {
            funNivel.setEnabled(true);
            funFuncao.setEnabled(false);
            funTitulacao.setEnabled(true);
            funArea.setEnabled(false);
            funCargaH.setEnabled(true);

            funNivel.removeAllItems();
            funNivel.addItem ("S1");
            funNivel.addItem ("S2");
        }
    }//GEN-LAST:event_funTipoActionPerformed

    private void funNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funNomeActionPerformed

    private void relatorioFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioFunActionPerformed
        
        Controlador controlador = new Controlador();
        
        String relatorio = "";
        
        if (escolhaFun.getSelectedItem() == "Todos"){
            
            relatorio = controlador.ExibirTodosOsFuncionários();
        }
        
        else if (escolhaFun.getSelectedItem() == "Faixa específica"){
            
            try {
                double faixaInicial = Double.parseDouble(faixaIniFun.getText());
                double faixaFinal = Double.parseDouble(faixaFimFun.getText());

                if (faixaInicial < faixaFinal){

                    relatorio = controlador.FuncionáriosComSalárioEmFaixaEspecífica(faixaInicial, faixaFinal);
                }

                else {
                    JOptionPane.showMessageDialog(null, "Faixas informadas incoerentes");
                }
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Informe as faixas");
            }
        }
        
        else if (escolhaFun.getSelectedItem() == "Técnicos"){
            
            relatorio = controlador.ExibirTodosOsTécnicos();
            
            
            
        }
        
        else if (escolhaFun.getSelectedItem() == "Docentes"){
            
            relatorio = controlador.ExibirTodosOsDocentes();
            
            
        }
        
        else if (escolhaFun.getSelectedItem() == "Docentes efetivos"){
            
            relatorio = controlador.ExibirTodosOsDocentesEfetivos();
            
            
            
        }
        else {
            
            relatorio = controlador.ExibirTodosOsDocentesSubstitutos();
            
        }
        
        
        areaTexto4.setText(relatorio);
        
        
    }//GEN-LAST:event_relatorioFunActionPerformed

    private void escolhaFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolhaFunActionPerformed
        
        if (escolhaFun.getSelectedItem() == "Faixa específica"){   
            faixaIniFun.setEnabled(true);
            faixaFimFun.setEnabled(true);
        }
        else {
            faixaIniFun.setEnabled(false);
            faixaFimFun.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_escolhaFunActionPerformed

    private void faixaIniFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faixaIniFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faixaIniFunActionPerformed

    private void buscarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDepActionPerformed
        
        Controlador control = new Controlador();
        String relatorio = "";
                   
            String codigo = buscarDepartamento.getText();
            
            try {
                
                int cod = Integer.valueOf(codigo);
                relatorio = control.ExibirInformaçõesDeUmDepartamento(codigo);
                
            } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, "Informe o código do departamento");
            }
            
       
        
        areaTexto5.setText(relatorio);
        
        
        
    }//GEN-LAST:event_buscarDepActionPerformed

    private void buscarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarDepartamentoActionPerformed

    private void buscarFunCodNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFunCodNomeActionPerformed
        
        String relatorio = "";
        
        Controlador control = new Controlador();
        
        if (buscarFun.getSelectedItem() == "Nome"){
            String nome = buscarNome.getText();
            
            relatorio = control.BuscarUmFuncionáriosPeloNome(nome);
            
        }
        else {
            
            try {
                
                int codigoVericacao = Integer.parseInt(buscarCod.getText());
                
                String cod = buscarCod.getText();
            
                relatorio = control.BuscarUmFuncionáriosPeloCódigo(cod);
                
                
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(null, "Informe o código");
                
            }
            
        }
        
        
        areaTexto6.setText(relatorio);
        
    }//GEN-LAST:event_buscarFunCodNomeActionPerformed

    private void buscarCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarCodActionPerformed

    private void buscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarNomeActionPerformed

    private void buscarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFunActionPerformed
        
        if (buscarFun.getSelectedItem() == "Nome"){
            buscarCod.setEnabled(false);
            buscarNome.setEnabled(true);
        }
        else {
            buscarCod.setEnabled(true);
            buscarNome.setEnabled(false);
        }
        
    }//GEN-LAST:event_buscarFunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JTextArea areaTexto2;
    private javax.swing.JTextArea areaTexto4;
    private javax.swing.JTextArea areaTexto5;
    private javax.swing.JTextArea areaTexto6;
    private javax.swing.JTextField buscarCod;
    private javax.swing.JButton buscarDep;
    private javax.swing.JTextField buscarDepartamento;
    private javax.swing.JComboBox<String> buscarFun;
    private javax.swing.JButton buscarFunCodNome;
    private javax.swing.JTextField buscarNome;
    private javax.swing.JButton cadastrarDep;
    private javax.swing.JButton cadastrarFun;
    private javax.swing.JTextField depNome;
    private javax.swing.JComboBox<String> escolhaDep;
    private javax.swing.JComboBox<String> escolhaFun;
    private javax.swing.JTextField faixaFim;
    private javax.swing.JTextField faixaFimFun;
    private javax.swing.JTextField faixaIni;
    private javax.swing.JTextField faixaIniFun;
    private javax.swing.JComboBox<String> funArea;
    private javax.swing.JComboBox<String> funCargaH;
    private javax.swing.JTextField funDepartamento;
    private javax.swing.JComboBox<String> funFuncao;
    private javax.swing.JComboBox<String> funNivel;
    private javax.swing.JTextField funNome;
    private javax.swing.JComboBox<String> funTipo;
    private javax.swing.JComboBox<String> funTitulacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton relatorioDeps;
    private javax.swing.JButton relatorioFun;
    private javax.swing.JButton relatorioGeral;
    // End of variables declaration//GEN-END:variables
}
